server:
  port: 9999


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: mcrservice1
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceA/**
        - id: microservice2
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceB/**
